export const allCases = [
    { id: 1, title: 'Accelerating Prosperity', type: 'Growth', difficulty: 'Easy', company: 'Kepler Cannon', problem: 'How would you, as a consultant, for PM Modi, advise him to grow the GDP of India faster than any other country and generate lots of jobs in the process? The aim is prosperity and has to be done by our recommendation only.'},
    { id: 2, title: 'An Apple a Day', type: 'Unconventional', difficulty: 'Easy', company: 'Accenture Strategy', problem: "You're a part of Apple's strategy team. Apple is considering to start renting out earphones on an early basis, should they go ahead with it or not?"},
    { id: 3, title: 'Brewing Success', type: 'Market Entry', difficulty: 'Moderate', company: 'Accenture Strategy', problem: 'You have to open a coffee shop in Delhi. What are the factors you would consider?'},
    { id: 4, title: 'Bucks over Brands', type: 'Market Entry', difficulty: 'Moderate', company: 'LEK Capability Network', problem: 'Your Company has 2 online retail shops, one is a premium retail shop and the other one is a cheap retail shop. Both are very similar in nature, so figure out the possible reasons as to why the cheaper retail store has a higher profit margin than the premium shop.'},
    { id: 5, title: 'Building the Bank', type: 'Profitability', difficulty: 'High', company: 'McKinsey & Co.', problem: 'The client in a Banking Client from a large private sector firm - like Axis Bank- in India. The company wants to start a 3-in-1 account: a savings account + DMAT account + Trading account. The company already has a customer base of 5 million people. How would you determine how many people are interested to sign up for this?'},
    { id: 6, title: 'Can Taylor Swift come to India?', type: 'Profitability', difficulty: 'High', company: 'McKinsey & Co.', problem: 'You are Taylor Swift’s Brand Manager. Do you think Taylor swift should enter the Indian Market? Give a complete financial analysis with relevant justifications.'},
    { id: 7, title: 'Can the ants cross each other?', type: 'Unconventional', difficulty: 'Moderate', company: 'Bain Capability Network', problem: "There is an equilateral triangle and there is an ant present at each end. What is the probability that these ants don't cross each other?"},
    { id: 8, title: 'Candy Catastrophe', type: 'Profitability', difficulty: 'Moderate', company: 'Accenture Strategy', problem: 'Your client is an FMCG manufacturer comparable to Cadbury. The company has been facing a decline in profits. Help them figure out the exact reason for this decline.'},
    { id: 9, title: 'Cash Capsule', type: 'Profitability', difficulty: 'Moderate', company: 'McKinsey & Co.', problem: 'Your client is a pharmaceutical company in the USA. They have finished phase 3 trials of a pill. Its price is $2, and it treats a neurological disorder. You are required to calculate the revenue for the first year.'},
    { id: 10, title: 'Chic Expansion', type: 'Market Entry', difficulty: 'Moderate', company: 'BOD Consulting', problem: 'You are based in London, UK, and own a chain of fashion retailers. You feel that you have saturated your market in the UK. The company wants you to identify the factors to be considered in this entire decision-making process.'},
    { id: 11, title: 'Childhood Shield', type: 'Unconventional', difficulty: 'High', company: 'McKinsey & Co.', problem: 'A disease is spreading in South Africa that primarily affects children, and it can be contained through vaccination. However, a substantial portion of the population has not received vaccination. How would you approach this problem?'},
    { id: 12, title: 'Coffee Madness', type: 'Market Entry', difficulty: 'Easy', company: 'Accenture Strategy', problem: 'A coffee shop wants to enter the Delhi University Market. Should it? Why or why not?'},
    { id: 13, title: 'Cracking the Tile', type: 'Profitability', difficulty: 'Moderate', company: 'Boston Consulting Group', problem: "Your client is a tile manufacturing company, operating in the whole of India. They're facing a fall in their profits, in West and South Delhi. They're not facing this decline in the northern part. A 2-3% fall in the market share and a 15-18% fall in profits. Within India, we're ranked 5th as the tile manufacturing company. Awareness is the same in north and south, while consideration is one third. What according to you are the potential reasons?"},
    { id: 14, title: 'Data Insight', type: 'Unconventional', difficulty: 'High', company: 'McKinsey & Co.', problem: 'Devise ways to leverage the data Like customer names, the number of watches purchased, and their addresses for understanding consumer behaviour, and preferences, and potentially improving business strategies for the watch shop.'},
    { id: 15, title: "Don't Sugarcoat it!", type: 'Profitability', difficulty: 'Easy', company: 'Nation with Namo', problem: 'Your client is a sugarcane factory in India. The company is facing stagnant profits. You need to find the reasons for the problem.'},
    { id: 16, title: 'Droned Crops!', type: 'Market Entry', difficulty: 'Moderate', company: 'McKinsey & Co.', problem: 'Estimate the Market size of agricultural spray drones?'},
    { id: 17, title: 'Dynamic Democracy', type: 'Unconventional', difficulty: 'Easy', company: 'Nation With Namo', problem: 'Your client is a local successful businessman who is active socially with NGOs. He wants to stand as an independent candidate in the Shakarupur constituency. Advise the client on this political endeavor.'},
    { id: 18, title: 'Efficient Transit', type: 'Unconventional', difficulty: 'High', company: 'Kearney', problem: 'Our Client is the Ministry of Transport and they want to improve the logistical efficiency.'},
    { id: 19, title: 'Expansion Endeavours', type: 'Growth', difficulty: 'Moderate', company: 'Boston Consulting Group', problem: 'Your Client is a Non banking financial company and functions as a public sector undertaking. Suggest a suitable growth strategy.'},
    { id: 20, title: 'Fitness Finances', type: 'Market Entry', difficulty: 'Moderate', company: 'LEK Capability Network', problem: 'Your client is a health tech startup that manufactures special wearable devices like smartwatches or shoulder pads which measure the fitness of an individual. The company caters to the age group of 25-45 years. The price of one watch is $150. Calculate the annual revenue in the target market having 40 health-tech startups and the profit per unit.'},
    { id: 21, title: 'Get your Pulse on It', type: 'Market Entry', difficulty: 'Moderate', company: 'Bain Capability Network', problem: 'The manufacturer of a health-tech device is planning to launch the product in the US market. This is their very first product launch. Estimate their market size.'},
    { id: 22, title: 'Good and Excellent', type: 'Profitability', difficulty: 'Moderate', company: 'LEK Capability Network', problem: 'There are two drink companies. One is named Good. Another is Excellent. They both have a steady revenue growth for the past five years and the market size of both these are the same. The Good profits have been steady but Excellent profits are fluctuating. Find reason for the fluctuating profits of Excellent company.'},
    { id: 23, title: 'Growth Beyond Borders', type: 'Market Entry', difficulty: 'High', company: 'LEK Capability Network', problem: 'Your client is a fast fashion retail chain called My Brands. They have a considerable market share in the US economy but are now facing market saturation. They want to expand to new geographies but aren’t sure where to expand. Your task is to first list down the different factors to evaluate a potential geography to which they can extend their operations and state what strategies you would use to enter that particular country or geography.'},
    { id: 24, title: 'Home Haven Expansion', type: 'Growth', difficulty: 'Moderate', company: 'Redseer Consulting', problem: 'Our Client Amazon India is growing in the home furnishing industry and they want to grow faster.'},
    { id: 25, title: 'Hotel Shotel', type: 'Market Entry', difficulty: 'High', company: 'Kearney', problem: 'Your client is a large hotel chain that wishes to enter the Indian market. How would you advise them to go about it?'},
    { id: 26, title: 'Ink In or Ink Out?', type: 'Market Entry', difficulty: 'High', company: 'Accenture Strategy', problem: 'Your client is a paper manufacturing company based out of Indonesia. They operate in the B2B space and sell paper to publishing houses. They are considering expanding operations by entering India. Ascertain if this is a good strategy.'},
    { id: 27, title: 'Learning the English Way', type: 'Unconventional', difficulty: 'High', company: 'Alvarez and Marsal', problem: 'Your client is Vedantu and Indian edtech giant seeking to enter three European countries. Give four parameters that you would consider with your rationale behind it.'},
    { id: 28, title: 'LifeEpic Launch', type: 'Market Entry', difficulty: 'Moderate', company: 'LEK Capability Network', problem: 'Your client is a major magazine publisher based in the US. It is considering the idea of launching a new lifestyle magazine. Analyse and recommend if he should go ahead with this idea.'},
    { id: 29, title: 'Lights, Camera, Fashion!', type: 'Market Entry', difficulty: 'High', company: 'LEK Capability Network', problem: 'Your client is a fashion retail brand called Watson. They are based in the US and are looking to expand because the US market has matured. Identify which market they should enter and create a framework to devise a checklist for evaluating countries to streamline entry decisions.'},
    { id: 30, title: 'Logistics Boost', type: 'Unconventional', difficulty: 'High', company: 'Kearney', problem: 'Our Client is the Ministry of Transport and they want to improve the logistical efficiency. You can talk about an approach to calculate the demand for roads at any point in time.'},
    { id: 31, title: 'Lubricant Lament', type: 'Growth', difficulty: 'Moderate', company: 'Boston Consulting Group', problem: 'Your Client is a lubricant player for 10 years in the Indian Market. They are ranked 3rd globally, and 8th in India. However, they are struggling with their Indian Market Presence. They want an aggressive market growth strategy where they want to increase their market growth by 5 times in the coming 1-2 years.'},
    { id: 32, title: 'Lux Cabs but Lax Revenues', type: 'Profitability', difficulty: 'Moderate', company: 'LEK Capability Network', problem: 'There are two cab aggregators- Quickride and Lux Cabs. The revenue of the former is stable. However, that of the latter is fluctuating. You are the CEO and the other board members are quite agitated because of this. What solutions would you propose?'},
    { id: 33, title: 'Mad Amount of Angles', type: 'Profitability', difficulty: 'Easy', company: 'Boston Consulting Group', problem: "Your client is a potato snacks company in the Middle East. They're facing a gradual decline in their profits over the last five to six years. It was a gradual decline. Find out why."},
    { id: 34, title: 'Meat Me at our Spot', type: 'Unconventional', difficulty: 'Easy', company: 'Boston Consulting Group', problem: 'Your client is mock-meat manufacturer. Come at a particular income class of people who actually buy this product?'},
    { id: 35, title: 'Metals to Multiverse', type: 'Market Entry', difficulty: 'High', company: 'Kepler Cannon', problem: 'Your client is running a Mining and Metals Company. Now, they want to enter different industries. How would you go about evaluating its options?'},
    { id: 36, title: 'Not a Coin Toss', type: 'Unconventional', difficulty: 'Moderate', company: 'Nation with Namo', problem: 'There is an election and two candidates are being considered for it. Compare two candidates for the same.'},
    { id: 37, title: 'Party at the Polls', type: 'Unconventional', difficulty: 'Moderate', company: 'Nation With Namo', problem: 'Develop a strategy to engage young, first-time voters in your area and encourage them to vote for your party.'},
    { id: 38, title: 'Pigment Prospects', type: 'Market Entry', difficulty: 'Moderate', company: 'McKinsey & Co.', problem: 'The client specializes in producing pigments used in household paints and cosmetics. As a family-run business, they are looking to invest and are deciding between the house paint and makeup segments. Their main objective is to improve their business and secure its future. Evaluate segments where they can diversify.'},
    { id: 39, title: 'Pipes to Progress', type: 'Growth', difficulty: 'High', company: 'Kearney', problem: "Our client is an iron pipe manufacturing company. Their revenues have been stagnant, and they're seeking ways to increase growth. What approach would you suggest?"},
    { id: 40, title: 'Potato Potahto', type: 'Profitability', difficulty: 'Easy', company: 'Bain Capability Network', problem: "Your client is a potato snacks company in the Middle East. They're facing a gradual decline in their profits over the last five to six years. And you need to find out the reason for the decline. Additionally, it was a gradual decline."},
    { id: 41, title: 'Profit Puzzle', type: 'Profitability', difficulty: 'High', company: 'LEK Capability Network', problem: 'In the US market, there are two online retailers, Budget Mart and Elite Goods. Budget Mart provides budget-friendly goods to consumers, and Elite Goods caters to only the high-income groups, providing premium products at high prices. The revenue of Budget Mart is $100 million, and for Elite Goods, it is $120 million dollars. However, the profit margin of Budget Mart is greater than the profit of Elite Goods. Your client is Elite Goods, and it wants you to identify why Budget Mart has greater profits even after catering to the lower-income category. As a consultant, you are required to pinpoint those key areas due to which Elite Goods might be facing the problem.'},
    { id: 42, title: 'Profit Revive', type: 'Profitability', difficulty: 'Moderate', company: 'Accenture Strategy', problem: 'Your client is an owner of a toy store situated in a fairly busy area. The business is doing good. Revenues have increased and the cost has also not shown any alarming fluctuation. However, the profitability of the business is going down. Find out the reason and suggest remedies.'},
    { id: 43, title: 'Reading Revenues', type: 'Profitability', difficulty: 'High', company: 'Nation With Namo', problem: 'You are the Marketing Manager of your favourite author. Your task is to double the sales of your favourite book by this author. How would you do this?'},
    { id: 44, title: 'Retail Landscape Analysis', type: 'Market Entry', difficulty: 'High', company: 'Kearney', problem: 'Our Client is a high-end retail chain based in India. Estimate the market size and the number of supermarket stores that we could get for the client.'},
    { id: 45, title: 'Ride on Hotel California', type: 'Market Entry', difficulty: 'Moderate', company: 'Alvarez and Marsal', problem: 'A hotel wants to install an amusement park in the premises. What is your take on the same ?'},
    { id: 46, title: 'Sky High Harvest', type: 'Profitability', difficulty: 'Easy', company: 'Boston Consulting Group', problem: 'Your client is a tractor manufacturer. They have been facing a decline in sales for the past one year. You need to find out the reason for the decline.'},
    { id: 47, title: 'Sole Mates', type: 'Market Entry', difficulty: 'Easy', company: 'LEK Capability Network', problem: 'Your client is a sneaker manufacturer in the footwear industry and they are trying to expand into other sectors. Decode the factors that must be considered by the company to expand into a new sector. What products do you think they can enter into?'},
    { id: 48, title: 'Statistically Speaking', type: 'Unconventional', difficulty: 'Easy', company: 'Bain Capability Network', problem: 'You are running an election for the President of the Statistics Department. How do you run a successful campaign?'},
    { id: 49, title: 'The Dotcom Crisis', type: 'Market Entry', difficulty: 'Moderate', company: 'Indus Insights', problem: 'Your client is an e-commerce company. It’s looking to enter the US market. For their entry, they’re looking to market themselves through two different methods of SEO- banner ads and URL ads. Which type of ads should the company proceed with?'},
    { id: 50, title: 'The Fast & The Furious', type: 'Unconventional', difficulty: 'Moderate', company: 'Bain & Co.', problem: 'Your client has found a new method to transport people from India to the USA in just 30 minutes. Decide how to price this service.'},
    { id: 51, title: 'The Social Dilemma', type: 'Unconventional', difficulty: 'Moderate', company: 'Boston Consulting Group', problem: 'Your driver gets 20,000 rs. a month. He heard from somewhere that he can make more money if he joins Uber. Elaborate on what you think would be the right decision for him.'},
    { id: 52, title: 'Time in a Bottle', type: 'Market Entry', difficulty: 'Moderate', company: 'LEK Capability Network', problem: 'There is a healthcare company in the United States that makes products for various diseases, and now the company is planning to enter the smartwatch sector. What are the factors that you would consider?'},
    { id: 53, title: 'TimeWarp Travel', type: 'Pricing', difficulty: 'Moderate', company: 'Kearney', problem: 'Your client is an Airplane service provider. A new service has been introduced that enables you to travel from New Delhi to New York in just one hour, and they are promoting their brand based on the time-saving aspect of this service. How would you price this service?'},
    { id: 54, title: 'TRUCKload of Gasoline', type: 'Profitability', difficulty: 'Easy', company: 'LEK Capability Network', problem: 'Your client is a trucking company deciding between adopting an electric fleet or a gasoline fleet. As a consultant, determine the optimal choice.'},
    { id: 55, title: 'Unwaivering Allegiance', type: 'Unconventional', difficulty: 'Easy', company: 'Bain & Co.', problem: 'An e-commerce brand is trying to launch a loyalty programme, you are required to delve into the expected costs of the programme.'},
    { id: 56, title: 'Where are the Kids?', type: 'Unconventional', difficulty: 'Easy', company: 'Nation with Namo', problem: 'Elections often face apathy from certain sections of society like women, the elderly etc. How would you increase youth participation in election?'}
];
export const casebooks = {
    1: 'cases/Accelerating Prosperity II Growth II Easy II Kepler Cannon.pdf',
    2: 'cases/An Apple a Day II Unconventional II Easy II Accenture Strategy.pdf',
    3: 'cases/Brewing Success II Market Entry II Moderate II Accenture Strategy.pdf',
    4: 'cases/Bucks over Brands II Market Entry II Moderate II LEK Capability Network.pdf',
    5: 'cases/Building the Bank II Profitability II High II McKinsey & Co..pdf',
    6: 'cases/Can Taylor Swift come to India II Profitability II High II McKinsey & Co..pdf',
    7: 'cases/Can the ants cross each other II Unconventional II Moderate II Bain Capability Network.pdf',
    8: 'cases/Candy Catastrophe II Profitability II Moderate II Accenture Strategy.pdf',
    9: 'cases/Cash Capsule II Profitability II Moderate II McKinsey & Co..pdf',
    10: 'cases/Chic Expansion II Market Entry II Moderate II BOD Consulting.pdf',
    11: 'cases/Childhood Shield II Unconventional II High II McKinsey & Co..pdf',
    12: 'cases/Coffee Madness II Market Entry II Easy II Accenture Strategy.pdf',
    13: 'cases/Cracking the Tile II Profitability II Moderate II Boston Consulting Group.pdf',
    14: 'cases/Data Insight II Unconventional II High II McKinsey & Co..pdf',
    15: "cases/Don't Sugarcoat it! II Profitability II Easy II Nation with Namo.pdf",
    16: 'cases/Droned Crops! II Market Entry II Moderate II McKinsey & Co..pdf',
    17: 'cases/Dynamic Democracy II Unconventional II Easy II Nation With Namo.pdf',
    18: 'cases/Efficient Transit II Unconventional II High II Kearney.pdf',
    19: 'cases/Expansion Endeavours II Growth II Moderate II Boston Consulting Group.pdf',
    20: 'cases/Fitness Finances II Market Entry II Moderate II LEK Capability Network.pdf',
    21: 'cases/Get your Pulse on It II Market Entry II Moderate II Bain Capability Network.pdf',
    22: 'cases/Good and Excellent II Profitability II Moderate II LEK Capability Network.pdf',
    23: 'cases/Growth Beyond Borders II Market Entry II High II LEK Capability Network.pdf',
    24: 'cases/Home Haven Expansion II Growth II Moderate II Redseer Consulting.pdf',
    25: 'cases/Hotel Shotel II Market Entry II High II Kearney.pdf',
    26: 'cases/Ink In or Ink Out II Market Entry II High II Accenture Strategy.pdf',
    27: 'cases/Learning the English Way II Unconventional II High II Alvarez and Marsal.pdf',
    28: 'cases/LifeEpic Launch II Market Entry II Moderate II LEK Capability Network.pdf',
    29: 'cases/Lights, Camera, Fashion! II Market Entry II High II LEK Capability Network.pdf',
    30: 'cases/Logistics Boost II Unconventional II High II Kearney.pdf',
    31: 'cases/Lubricant Lament II Growth II Moderate II Boston Consulting Group.pdf',
    32: 'cases/Lux Cabs but Lax Revenues II Profitability II Moderate II LEK Capability Network.pdf',
    33: 'cases/Mad Amount of Angles II Profitability II Easy II Boston Consulting Group.pdf',
    34: 'cases/Meat Me at our Spot II Unconventional II Easy II Boston Consulting Group.pdf',
    35: 'cases/Metals to Multiverse II Market Entry II High II Kepler Cannon.pdf',
    36: 'cases/Not a Coin Toss II Unconventional II Moderate II Nation with Namo.pdf',
    37: 'cases/Party at the Polls II Unconventional II Moderate II Nation With Namo.pdf',
    38: 'cases/Pigment Prospects II Market Entry II Moderate II McKinsey & Co..pdf',
    39: 'cases/Pipes to Progress II Growth II High II Kearney.pdf',
    40: 'cases/Potato Potahto II Profitability II Easy II Bain Capability Network.pdf',
    41: 'cases/Profit Puzzle II Profitability II High II LEK Capability Network.pdf',
    42: 'cases/Profit Revive II Profitability II Moderate II Accenture Strategy.pdf',
    43: 'cases/Reading Revenues II Profitability II High II Nation With Namo.pdf',
    44: 'cases/Retail Landscape Analysis II Market Entry II High II Kearney.pdf',
    45: 'cases/Ride on Hotel California II Market Entry II Moderate II Alvarez and Marsal.pdf',
    46: 'cases/Sky High Harvest II Profitability II Easy II Boston Consulting Group.pdf',
    47: 'cases/Sole Mates II Market Entry II Easy II LEK Capability Network.pdf',
    48: 'cases/Statistically Speaking II Unconventional II Easy II Bain Capability Network.pdf',
    49: 'cases/The Dotcom Crisis II Market Entry II Moderate II Indus Insights.pdf',
    50: 'cases/The Fast & The Furious II Unconventional II Moderate II Bain & Co..pdf',
    51: 'cases/The Social Dilemma II Unconventional II Moderate II Boston Consulting Group.pdf',
    52: 'cases/Time in a Bottle II Market Entry II Moderate II LEK Capability Network.pdf',
    53: 'cases/TimeWarp Travel II Pricing II Moderate II Kearney.pdf',
    54: 'cases/TRUCKload of Gasoline II Profitability II Easy II LEK Capability Network.pdf',
    55: 'cases/Unwaivering Allegiance II Unconventional II Easy II Bain & Co..pdf',
    56: 'cases/Where are the Kids II Unconventional II Easy II Nation with Namo.pdf',
    default: 'cases/Accelerating Prosperity II Growth II Easy II Kepler Cannon.pdf'
};

export const mascots = [
    { id: 0, color: '#3b82f6', shadow: 'rgba(59, 130, 246, 0.25)' }, // Blue
    { id: 1, color: '#6366f1', shadow: 'rgba(99, 102, 241, 0.25)' }, // Indigo
    { id: 2, color: '#10b981', shadow: 'rgba(16, 185, 129, 0.25)' }, // Emerald
    { id: 3, color: '#f59e0b', shadow: 'rgba(245, 158, 11, 0.25)' }, // Amber
    { id: 4, color: '#64748b', shadow: 'rgba(100, 116, 139, 0.25)' }, // Slate
];

export const commonAvatarSvg = `
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-full h-full">
        <path fill-rule="evenodd" d="M7.5 6a4.5 4.5 0 1 1 9 0 4.5 4.5 0 0 1-9 0ZM3.751 20.105a8.25 8.25 0 0 1 16.498 0 .75.75 0 0 1-.437.695A18.683 18.683 0 0 1 12 22.5c-2.786 0-5.433-.608-7.812-1.7a.75.75 0 0 1-.437-.695Z" clip-rule="evenodd" />
    </svg>
`;
